### ISSUE TITLE
Adding a middleware after metadate middleware

### ISSUE THREAD

**Issue by GiladShoham** [theganyo/swagger-node-runner#11]
Hi, 
I have some middleware which check permission for specific API.
The validation is against path in a rules manifest like user/create.
until now i use it from express like this: 
```
app.post("/user", permissionMW("users/create"), myControllerFunc);
```
Now i want to move this manifest path to be in the swagger yaml with x-permission-path.
but to use it i need to add this middleware to run after the metadate middleware (before/after the security middleware). so i will have access to the swagger object.
I want to somehow pass an hook MW which i can define from outside when to run it, and provide the func.
something like add to the config in the constructor:
```js
MWhooks : {
"before[MWname]" : [myMW1, myMW2],
"after[MWname]" :  [myMW3, myMW4]
}
```
an actual value for this example will be :

```js
myMW1 = function(req, res, next){
 if something next();
 throw err;
}
MWhooks  =  {
 "aftersecurity" :  [myMW1]
}

var config  = {
 MWhooks  : MWhooks 
}

Runner.create(config, function(err, runner) {
    if (err) { return cb(err); }
    cb(undefined, runner.expressMiddleware());
  });
```

What do you think about this? is this sound like a good solution?

**Comment by theganyo** [comment]
Why, yes, actually! It's great that you bring this up because I'm working on a plugin solution even as I type this. I've identified several phases that I'm working with right now (though I'm open for suggestions):

'preprocess', 'preauth', 'auth', 'preflight', and 'postflight'

The idea is that, similar to what you mention, a plugin (middleware) would be have a chance to execute in the phase that is appropriate. The entire lifecycle would be:

request -> proprocess -> metadata -> preauth -> auth -> preflight -> router/controller -> postflight

**Comment by GiladShoham** [comment]
I think it's a great feature.
I need it very much, so it's nice to know that you are working it.
about the events them self, i saw in the code those mw
```js
var middlewares = [
      this.metadata(),
      this.security(),
      this.validator(),
      this.expressCompatibilityMW(),
      this.router()
    ];
```
so im not sure if i understand when is the preflight will run, it could be after security after validator or after expressCompatibilityMW.
maybe you should add some more events? or at least document when exactly the event will triggered.

Actually i'm building right now a really massive infrastructure with swagger and this is one of my big missing part.
so if you have any estimation on schedule for this, it will be great.
if it will take you long time of course i can help, and maybe i will write something in the meantime just so my other developers will be able to work on the actual API using the new infra.

Thx a lot, and i'm here for help:)  

P.S - if you can help me with the testing for the 2 other pull request i have sent it will be awesome, because i won't have time for adding testing until this infra will be ready because all of my developers waiting for this.

**Comment by theganyo** [comment]
Yes, actually, since posting that I've been revamping my thoughts on it. I'm hoping to make it much easiest for apps to take full control of the lifecycle instead of being limited to specific events. I'll post more on it soon and maybe we can collaborate on this.

If you need something immediately, though, all the individual pieces are already available without having to fork. As you've seen, the middlewares are currently all exposed to your app, so you can register them yourself instead of calling register() if you wish. That would allow you to put your middleware anywhere in the chain.

**Comment by GiladShoham** [comment]
ok, i will do my best to give you some inputs when you post about it.

in the meantime, i didn't saw an option to register them by my self.
can you elaborate a bit on how to do this? or maybe give me a simple example?

Thx a lot.

**Comment by theganyo** [comment]
You bet. For now, you could access and use the middleware directly something like this:

```
SwaggerConnect.create(config, function(err, swaggerConnect) {
  if (err) { throw err; }

  // install middleware individually instead of using register()
  app.use(swaggerConnect.metadata());
  app.use(swaggerConnect.security());
  app.use(swaggerConnect.validator());
  // etc...
```

Now, I'm not recommending this as a procedure going forward because it's very likely that my work mentioned above will break it... but it will work for now, give you the flexibility you need, and I expect it will be able to be easily upgraded to the new version when that happens.

**Comment by theganyo** [comment]
FYI, the new beta addresses middleware pipelines: https://github.com/swagger-api/swagger-node/issues/294

**Comment by GiladShoham** [comment]
@theganyo 
Looks great.
i will play with it in a few days, and convert my existing hack for adding the mw, to the pipes standards.
now, i only need someone to merge my pr to swagger-tools:
https://github.com/apigee-127/swagger-tools/pull/260
https://github.com/apigee-127/swagger-tools/pull/253
