### ISSUE TITLE
npm `config` dependency

### ISSUE THREAD

**Issue by kayomarz** [theganyo/swagger-node-runner#60]
My application depends upon npm module [swagger-express-mw](https://www.npmjs.com/package/swagger-express-mw) which in turn depends on this project.

This project (`swagger-node-runner`) depends on npm module  [config](https://www.npmjs.com/package/config)

Since my application also depends on npm module  [config](https://www.npmjs.com/package/config), I think it's causing a conflict because this `config` module expects a single configuration directory relative to the current working directory of the process.

The outcome is that when I run the application, I think `swagger-node-runner` must be reading my application `config` files instead of the intended config. (`swagger-node-runner` doesn't report an error)

I might be wrong about `swagger-node-runner` getting hold of the application config file instead of the intended `config` file but that's my reasoning based on how the `config` module works.

Does anyone have any inputs as to what might be happening and the correct way of handling this problem?

btw, Is `config` needed only to run the swagger editor? Or is it needed by middleware to serve a live API.

**Comment by osher** [comment]
Basically, yes - there should be one file, and this file should contain your configuration AND whatever is needed to configure swagger-node-runner.
That's why it wraps all it's settings under the key `swagger:`. Everything outside this is ...just yours :)

In that sense, I can't understand how you have separate files for swagger-node-runner and for you app.
Would you mind to describe your folder structure?
